### ISSUE TITLE
Consulta sobre la aplicación Guardian

### ISSUE THREAD

**Issue by jcrequena** [agaraycanas/guardian#1]
Buenos días Alberto,soy Juan Carlos profesor de un instituto de Castellón. Estuve leyendo tu proyecto GUARDIAN para la gestión de guardias de profesores de un IES en github y tengo una duda, en algunos de los controladores llamas a la función enmarcar ( $this, 'curso/crear' ); pero no veo que la tengas declarada (su funcionalidad) en ningún fichero, por lo que que cuando pruebo la App, me da un error en el Home.php ya que no encuentra la función. ¿Podrías indicarme cómo podría resolverlo?.Muchas gracias y enhorabuena por la aplicación que has hecho!Saludos.
Juan Carlos.

**Comment by agaraycanas** [comment]
Hola Juan Carlos,

Por desgracia, este proyecto no lo completé en su momento y lo tengo abandonado. Estaba metido en otro, para llevar encuestas de calidad, y mi idea era,que en cuanto fuera estable, añadirle las funcionalidades de este primer proyecto "Guardian".

Siento no ser más de ayuda. Si alguna parte del código que he hecho te sirve para hacer lo que quieras, siéntete libre de utilizarlo.

Gracias

PD: Al final, en mi instituto las guardias se siguen llevando con papeles, aunque yo intenté al menos, que fuera con una hoja de cálculo. Poco a poco. Además, hoy en día, con la que está cayendo, pocas guardias estamos haciendo ;-D

**Comment by jcrequena** [comment]
Buenas tardes,
muchas gracias por tu respuesta. Bueno, tu proyecto puede ser una buena base para conseguir tener algo funcional.
Gracias de nuevo.
Saludos.

Juan Carlos.
